version: '3'

services: 
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=banheiro_limpo
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - /data/mysql
  
  docker-banheirolimpo-service:
    image: banheirolimpo-service
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/banheirolimpo-service
    depends_on:
      - mysql-docker-container
    ports:
      - 8080:8080
    