version: '3'

services: 
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=banheiro_limpo
      - MYSQL_PASSWORD=root
  spring-boot-jpa-docker-webapp:
    image: docker-banheirolimpo-service
    depends_on:
      - docker-mysql
    ports:
      - 8081:8080
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=banheiro_limpo  
      - DATABASE_PORT=3306